name: Unit tests

on: [ push, pull_request ]

jobs:
  run:
    runs-on: "ubuntu-latest"
    name: Test Laravel ${{ matrix.laravel-version }} on PHP ${{ matrix.php-version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 5.0 runs on PHP 5.4 - 5.6, but phpunit requires 5.6 for mock objects
          #- laravel-version: "5.0"
          #  php-version: "5.4"
          #- laravel-version: "5.0"
          #  php-version: "5.5"
          - laravel-version: "5.0"
            php-version: "5.6"
          - laravel-version: "5.0"
            php-version: "7.0"
          # Laravel 5.1 runs on PHP 5.5 - 5.6, but phpunit requires 5.6 for mock objects
          #- laravel-version: "5.1"
          #  php-version: "5.5"
          - laravel-version: "5.1"
            php-version: "5.6"
          # Laravel 5.2 runs on PHP 5.5 - 7.1, but phpunit requires 5.6 for mock objects
          #- laravel-version: "5.2"
          #  php-version: "5.5"
          - laravel-version: "5.2"
            php-version: "5.6"
          - laravel-version: "5.2"
            php-version: "7.0"
          - laravel-version: "5.2"
            php-version: "7.1"
          # Laravel 5.3 runs on PHP 5.6 - 7.1
          - laravel-version: "5.3"
            php-version: "5.6"
          - laravel-version: "5.3"
            php-version: "7.0"
          - laravel-version: "5.3"
            php-version: "7.1"
          # Laravel 5.4 runs on PHP 5.6 - 7.1
          - laravel-version: "5.4"
            php-version: "5.6"
          - laravel-version: "5.4"
            php-version: "7.0"
          - laravel-version: "5.4"
            php-version: "7.1"
          # Laravel 5.5 runs on PHP 7.0 - 7.4
          - laravel-version: "5.5"
            php-version: "7.0"
          - laravel-version: "5.5"
            php-version: "7.1"
          - laravel-version: "5.5"
            php-version: "7.2"
          - laravel-version: "5.5"
            php-version: "7.3"
          - laravel-version: "5.5"
            php-version: "7.4"
          # Laravel 5.6 runs on PHP 7.1 - 7.4
          - laravel-version: "5.6"
            php-version: "7.1"
          - laravel-version: "5.6"
            php-version: "7.2"
          - laravel-version: "5.6"
            php-version: "7.3"
          - laravel-version: "5.6"
            php-version: "7.4"
          # Laravel "5.7" runs on PHP 7.1 - 7.4
          - laravel-version: "5.7"
            php-version: "7.1"
          - laravel-version: "5.7"
            php-version: "7.2"
          - laravel-version: "5.7"
            php-version: "7.3"
          - laravel-version: "5.7"
            php-version: "7.4"
          # Laravel 5.8 runs on PHP 7.1 - 7.4
          - laravel-version: "5.8"
            php-version: "7.1"
          - laravel-version: "5.8"
            php-version: "7.2"
          - laravel-version: "5.8"
            php-version: "7.3"
          - laravel-version: "5.8"
            php-version: "7.4"
          # Laravel 6.x runs on PHP 7.2 - 8.0
          - laravel-version: 6
            php-version: "7.2"
          - laravel-version: 6
            php-version: "7.3"
          - laravel-version: 6
            php-version: "7.4"
          - laravel-version: 6
            php-version: "8.0"
          # Laravel 7.x runs on PHP 7.2 - 8.0
          - laravel-version: 7
            php-version: "7.2"
          - laravel-version: 7
            php-version: "7.3"
          - laravel-version: 7
            php-version: "7.4"
          - laravel-version: 7
            php-version: "8.0"
          # Laravel 8.x runs on PHP 7.3 - 8.1
          - laravel-version: 8
            php-version: "7.3"
          - laravel-version: 8
            php-version: "7.4"
          - laravel-version: 8
            php-version: "8.0"
          - laravel-version: 8
            php-version: "8.1"
          # Laravel 9.x runs on PHP 8.0 - 8.1
          - laravel-version: 9
            php-version: "8.0"
          - laravel-version: 9
            php-version: "8.1"

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - uses: actions/checkout@v2

      - run: composer validate

      - run: composer config allow-plugins.*/* true

      - run: composer require "illuminate/database ${{ matrix.laravel-version }}.*"

      - run: vendor/bin/phpunit

      #- run: if [ -f build/logs/clover.xml ]; then php vendor/bin/php-coveralls --verbose; fi
